# Generated by Django 4.2.11 on 2024-10-30 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(default=0, related_name='followme', to=settings.AUTH_USER_MODEL),
        ),
    ]
