# Generated by Django 4.2.11 on 2024-10-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='initial_price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
