# Generated by Django 4.2.11 on 2024-10-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
    ]
