# Generated by Django 4.2.11 on 2024-10-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bid_listing_alter_auctionlisting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bid',
        ),
    ]
