# Generated by Django 4.2.11 on 2024-10-30 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(default=0, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
